services:
  - type: web
    name: api-financeira
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api_financeira:app --bind 0.0.0.0:$PORT
    healthCheckPath: /health
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: FIREBASE_CREDENTIALS
        sync: false
      - key: API_HOST
        value: 0.0.0.0
  - type: worker
    name: bot-telegram
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python telegram_bot.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: FIREBASE_CREDENTIALS
        sync: false
      - key: API_URL
        fromService:
          type: web
          name: api-financeira
          envVarKey: RENDER_EXTERNAL_URL
